(function() {

    /* we have our service handler here to access the exercises API*/
    
    'use strict';
    angular
        .module('app.exercise')
        .factory('ExerciseService', ExerciseService);

    ExerciseService.$inject = ['$http', 'REQUEST'];

    function ExerciseService($http, REQUEST) {

        var url = REQUEST.Exercises;
        var service = {
            'getExercises' : getExercises,
            'getExercise' : getExercise,
            'deleteExercise' : deleteExercise,
            'addExercise' : addExercise,
            'updateExercise' : updateExercise
        };
        return service;

        ////////////

        function getExercises() {
            return $http.get(url)
                    .then(getComplete, getFailed);                    

            function getComplete(response) { 
                return response.data;
            }

            function getFailed(error) {
                return [];
            }
        }
        
         function getExercise(_id) {
            var oneUrl = url + '/' + _id;
            return $http.get(oneUrl)
                    .then(getComplete, getFailed);                    

            function getComplete(response) { 
                return response.data;
            }

            function getFailed(error) {
                return [];
            }
        }
        
        function deleteExercise(_id) {
            var delUrl = url + '/' + _id;
            
            return $http.delete(delUrl)
                    .then(getComplete, getFailed);                    

            function getComplete(response) { 
                return 'Delete Completed';
            }

            function getFailed(error) {
                return 'Delete Failed';
            }
        }
        
        
        function addExercise(data) {            
            return $http.post(url, data)
                    .then(getComplete, getFailed);                    

            function getComplete(response) { 
                return 'Exercise Added';
            }

            function getFailed(error) {
                return 'Exercise Add Failed';
            }
        }
        
        function updateExercise(_id, data) {
            var updateUrl = url + '/' + _id;
            
            return $http.put(updateUrl, data)
                    .then(getComplete, getFailed);                    

            function getComplete(response) { 
                return 'Exercise Updated';
            }

            function getFailed(error) {
                return 'Exercise Update Failed';
            }
        }
        
        

    }
    
})();

//    Services
//    ==================
//    Angular services are substitutable objects that are wired together using dependency injection (DI). You can use services to organize and share code across your app.
//
//    ##Angular services are:
//
//    - Lazily instantiated 
//            – Angular only instantiates a service when an application component depends on it.
//    - Singletons 
//            – Each component dependent on a service gets a reference to the single instance generated by the service factory.
